### ISSUE TITLE
Integration of MSIO in EBI Ontology Lookup Service

### ISSUE THREAD

**Issue by nilshoffmann** [ISA-tools/MSIO#10]
@proccaserra 
in order to be able to use MSIO parent terms in our cv-mapping file for mzTab-2 for metabolomics, we need to be able to resolve child <-> parent relationships. I currently use the EBI's OLS for that, however, MSIO is not available there (yet).

Alternative: if I can query another resource to resolve MSIO terms for me that would also work.

[Current Lookup Service](https://github.com/nilshoffmann/jmzTab-m/blob/master/validation/src/main/java/de/isas/mztab2/cvmapping/CvParameterLookupService.java)

**Comment by proccaserra** [comment]
@nilshoffmann MSIO is not yet served by ontology services as we had to check with MSI group for their blessing.  Now this is done, I need to obtain a purl from the OBO foundry. Once done, we'll ask to load in Bioportal and OLS. We'll let you know when this is operational.

**Comment by sneumann** [comment]
Great and looking forward to see that. Yours, Steffen

**Comment by hechth** [comment]
@sneumann @proccaserra @nilshoffmann are there any news on this?

**Comment by proccaserra** [comment]
Hi @hechth , this issue can be closed:

https://www.ebi.ac.uk/ols4/ontologies?search=MSIO

if you have terms requests, let me know , open issues or send PR.
