### ISSUE TITLE
“Illegal redeclarations of entities” when loading into Protégé

### ISSUE THREAD

**Issue by JKChang2015** [ISA-tools/MSIO#12]
When loading the MSIO-edit.owl ontology into Protégé, the following error occurs (once).

Level:       ERROR
Time:        1533309437054
Message:     Illegal redeclarations of entities: reuse of entity http://usefulinc.com/ns/doap#bug-database in punning not allowed [AnnotationProperty: bug-database, ObjectProperty: bug-database]

**Comment by agbeltran** [comment]
Thanks for reporting this @JKChang2015 - we were aware of this issue and will be fixed in the upcoming release.

**Comment by JKChang2015** [comment]
I tried the new released ontology still have the same problem.
